oakd:
  enable_imu: True
  enable_rgb_camera: True
  enable_depth_camera: True
  imu_hz: 100
  imu_timeout: 1.0
  imu_acceleration_covariance_diag: [0.02, 0.02, 0.02]
  imu_angular_velocity_covariance_diag: [0.001, 0.001, 0.001]
  imu_orientation_covariance_diag: [0.00001, 0.00001, 0.00001]
  rgb_camera_timeout: 5.0
  rgb_camera_frame: "oakd_rgb"
  rgb_camera_fps: 10.0
  enable_rgb_uvc: False
  rgb_camera_width: 640
  rgb_uvc_device_name: "/dev/video10"
  rgb_camera_height: 480
  depth_camera_timeout: 5.0
  depth_camera_frame: 'oakd_depth'
  depth_camera_fps: 10.0

ydlidar_ros2_driver_node:
  port: /dev/ttyUSB0
  frame_id: laser_frame
  ignore_array: ""
  baudrate: 128000
  lidar_type: 1
  device_type: 0
  sample_rate: 9
  intensity_bit: 0
  abnormal_check_count: 4
  fixed_resolution: true
  reversion: true
  inverted: true
  auto_reconnect: true
  isSingleChannel: false
  intensity: false
  support_motor_dtr: false
  angle_max: 180.0
  angle_min: -180.0
  range_max: 64.0
  range_min: 0.01
  frequency: 10.0
  invalid_range_is_inf: false
